# Generated by Django 3.2 on 2021-12-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('group', models.CharField(choices=[('Костюмы', 'Костюмы'), ('Брюки', 'Брюки'), ('Обувь', 'Обувь'), ('Пиджаки', 'Пиджаки')], default='Костюмы', max_length=20)),
                ('img', models.ImageField(default='notimg.jpg', upload_to='product_image')),
            ],
        ),
    ]
