# Generated by Django 3.2 on 2021-12-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Костюмы', 'Костюмы'), ('Обувь', 'Обувь'), ('Пиджаки', 'Пиджаки'), ('Брюки', 'Брюки')], default='Костюмы', max_length=20),
        ),
    ]
